pool: Default

trigger: 
  - master

steps:
  - task: SonarCloudPrepare@3
    inputs: 
      SonarCloud: SONAR_CLOUD
      scannerMode: other
      organization: springpetclinic-maven

  - task: maven@4
    inputs: 
      mavenPOMFile: pom.xml
      goals: package
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
  - task: CopyFiles@2
    inputs:
      contents: '**/spring-petclinic*.jar'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: $(Build.Repository.Name)
  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutsec: '300'