pool: Default

trigger:
  - rel_v1

variables:
  dockerImageName: "sharathchandra007/spring-petclinic"
  dockerImageTag: "83"

stages:
  - stage: continous_deployment
    jobs: 
      - job: 'deployment'
        displayName: 'deploy the cluster'
        steps:

          - task: CmdLine@2
            displayName: 'docker pull command'
            inputs:
              script: | # The script block allows you to specify the commands to execute in the task.
                docker pull $(dockerImageName): $(dockerImageTag)

          - task: Bash@3
            displayName: "teraform initialization"
            inputs:
              targetType: "inline"
              script: |
               terraform init 
               terraform apply -var-file="defaults.tfvars" -auto-approve
              workingDirectory: "./infra"   

          - task: Bash@3
            displayName: "Deploy to k8s"
            inputs:
              targetType: "inline"
              script: |
                kubectl apply -f spc-deployment.yaml
                kubectl get all
                   
