# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: Default

trigger: 
 - master

resources:
  repositories:
    - repository : reusabletemplates
      type: github
      name: 'sharathchandra0007/AzureDevOps_templates-'
      endpoint: 'github.com_sharathchandra0007'

steps:
  - template: maven//maven-pipeline.yaml@reusabletemplates '
  - task: SonarCloudPublish@3
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Quality Gate Result'
