# Starter pipeline

trigger:
  - master

pool: Default
  
steps:
  - task: JFrogMaven@1
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'install'
      artifactoryResolverService: 'JFROG_CLOUD'
      targetResolveReleaseRepo: 'SPRING'
      targetResolveSnapshotRepo: 'SPRING'
      artifactoryDeployService: 'JFROG_CLOUD'
      targetDeployReleaseRepo: 'SPRING'
      targetDeploySnapshotRepo: 'SPRING'
      javaHomeOption: 'JDKVersion'

  - task: SonarCloudPrepare@3
    inputs:
      SonarQube: 'SONAR_CLOUD'
      organization: 'springpetclinic-maven'
      scannerMode: 'other'    
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


