apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 4
  minReadySeconds: 5
  selector:
    matchLabels:
      app: spetclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: spetclinic
    spec:
      containers: 
        - image: sharathchandra007/spring-petclinic:83
          name: spring
          resources:
            requests:
              cpu: 100m
              memory: 64M
            limits:
              cpu: 500m
              memory: 256M
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    app: web
spec:
  selector:
    app: spetclinic
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080 
